GET http://localhost:3000/api/chatroom
###
GET http://localhost:3000/api/chatroom/id
###
POST http://localhost:3000/api/chatroom/
Content-Type: application/json

{
    "nickname": "malcolmx",
    "firstname": "John",
    "lastname": "Egbert",
    "mail": "superpowers@mail.com",
    "passwd": "1234"
}
###
PUT http://localhost:3000/api/chatroom/id
###
DELETE http://localhost:3000/api/chatroom/id