### Obtengo todos los mensajes
GET http://localhost:3000/api/message

### Obtengo un mensaje por id
GET http://localhost:3000/api/message/69b56093fdf0ce31e4a22754

###
POST http://localhost:3000/api/message/
Content-Type: application/json

{
    "body": "buenas tardes noches",
    "sender": "69c939986535a62b46204c1b",
    "chatroom": "69c93a366535a62b46204c1f"
}
###
PUT http://localhost:3000/api/message/69c93a7c6535a62b46204c20
Content-Type: application/json

{
    "body": "buenas noches",
    "sender": "69c939906535a62b46204c19",
    "chatroom": "69c93a366535a62b46204c1f"
}
###
DELETE http://localhost:3000/api/message/69c93a7c6535a62b46204c20