### Obtengo todos los mensajes
GET http://localhost:3000/api/message

### Obtengo un mensaje por id
GET http://localhost:3000/api/message/69b56093fdf0ce31e4a22754

### Obtengo mensajes por chat
GET http://localhost:3000/api/message/chat/69c9a7ce38c69d1ee79c0536/2

###
POST http://localhost:3000/api/message/
Content-Type: application/json

{
    "body": "buenas tardes noches",
    "sender": "69c939906535a62b46204c19",
    "receiver": "69c9a7ce38c69d1ee79c0536"
}
###
PATCH  http://localhost:3000/api/message/69c99a8108a2972414945b8f
Content-Type: application/json

{
    "body": "7 minutes is all i can spare to play with ya"
}
###
DELETE http://localhost:3000/api/message/69c93a7c6535a62b46204c20