GET http://localhost:3000/api/user
###
GET http://localhost:3000/api/user/69bc728dad104326fa44e7bd
###
POST http://localhost:3000/api/user/verify
Content-Type: application/json

{
    "nickname": "malcolm2",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "rusmanoctavio@gmail.com",
    "passwd": "1234"
}
###
POST http://localhost:3000/api/user/
Content-Type: application/json

{
    "nickname": "malcolm3",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "superpowers@gmail.com",
    "passwd": "1234",
    "admin": [],
    "chatrooms": []
}
###
PUT http://localhost:3000/api/user/69beb6f5a90e4291a3677e06
Content-Type: application/json

{
    "nickname": "malcolmx",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "superpowers@mail.com",
    "passwd": "1234",
    "chatrooms": [""]
}
###
DELETE http://localhost:3000/api/user/69c939986535a62b46204c1b