GET http://localhost:3000/api/user
###
GET http://localhost:3000/api/user/id
###
POST http://localhost:3000/api/user
###
PUT http://localhost:3000/api/user/id
###
DELETE http://localhost:3000/api/user/id