GET http://localhost:3000/api/user
###
GET http://localhost:3000/api/user/69c939906535a62b46204c19
###
GET http://localhost:3000/api/user/login/69c939946535a62b46204c1a
###
POST http://localhost:3000/api/user/verify
Content-Type: application/json

{
    "nickname": "m",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "rusmanoctavio@gmail.com",
    "passwd": "1234"
}
###
POST http://localhost:3000/api/user/
Content-Type: application/json

{
    "nickname": "thedud",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "stuka@gmail.com",
    "passwd": "12345678",
    "chatrooms": [],
    "messages": []
}
###
PATCH  http://localhost:3000/api/user/69c939906535a62b46204c19
Content-Type: application/json

{
    "passwd": "123444",
    "chatrooms": ["69c9aa1817be65126fb37929"]
}
###
DELETE http://localhost:3000/api/user/69d1124e910cbf869b6a86f4