GET http://localhost:3000/api/user
###
GET http://localhost:3000/api/user/69bb0bbeec7302b172e75d45
###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "nickname": "malcolmx",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "superpowers@mail.com",
    "passwd": "1234"
}
###
PUT http://localhost:3000/api/user/69bb0bbeec7302b172e75d45
Content-Type: application/json

{
    "nickname": "malcolmx2",
    "firstname": "John",
    "lastname": "Egbert",
    "email": "superpowers@mail.com",
    "passwd": "1234"
}
###
DELETE http://localhost:3000/api/user/69bb0bbeec7302b172e75d45